### ISSUE TITLE
Help with rendering of (r), (c), etc. using MathJax 3

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/hugo-bare-min-theme#11]
Hello @benide,

As you are the resident expert in MathJax 3, I thought you asking you about this here directly.

After updating hugo-bare-min-theme to use MathJax 3, the ox-hugo test site now also uses the same, but now this page, for example, does not render the same way: https://ox-hugo.scripter.co/test/posts/equations-with-r-c/.

Earlier (r) or (R) was getting converted to ®, and similar for (c), (tm). But now that is not happening.

Would you have some clue about this behavior change?

**Comment by benide** [comment]
Honestly I'm not sure why it was happening before, but it should never have happened in the first place. It's doing exactly what I would expect. Do you or one of your users have a use-case for that?

The other problem you mentioned in the other post is more serious, I'll reply there :)

**Comment by kaushalmodi** [comment]
Oops! Of course!

> Below, (r) or (R) should **not** get converted to ®

I missed reading that "not" in my own test. Sorry for this noise. Closing this issue.
