### ISSUE TITLE
Revert to MathJax 2 until MathJax 3 become stable?

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/hugo-bare-min-theme#12]
Revert https://github.com/kaushalmodi/hugo-bare-min-theme/commit/4958d996e3cc2c59d73b2c7d665105a64c7b24a5 for the time being.

Issues:
- https://github.com/kaushalmodi/hugo-bare-min-theme/issues/11
- https://github.com/kaushalmodi/ox-hugo/issues/297#issuecomment-546946076

**Comment by benide** [comment]
Hello again! FYI, 3.0.1 has been released and fixes everything we had noticed. https://github.com/mathjax/MathJax-src/releases/tag/3.0.1

**Comment by kaushalmodi** [comment]
Thanks for the update! I now brought back your changes so that MathJax 3 is used. Many thanks!
