### ISSUE TITLE
Replace taxonomy with pages

### ISSUE THREAD

**Issue by larrasket** [kaushalmodi/hugo-bare-min-theme#14]
How can I replace taxonomies (tags | categories) with page widget?

**Comment by kaushalmodi** [comment]
What is a "page widget"? Also note that this is a "bare bones" theme. It was designed to understand the inner variables in Hugo.

**Comment by larrasket** [comment]
I used to use widgets to edit header menu (e.g [[menu.main]]). The change I want to make is to replace tags/categories sections with a page link, I tried to do some manipulation in `lists.html` and other files, but it didn't work

**Comment by kaushalmodi** [comment]
Sorry, your question is still not clear to me. I am not familiar with "widgets" in Hugo. 

May you looking to modify this template and not list.html?: https://github.com/kaushalmodi/hugo-bare-min-theme/blob/master/layouts/_default/terms.html

Also reach out on the Hugo Discourse forum for Hugo-specific questions. The benefit there is that there will be a lot of active Hugo users who might answer your question quicker and more accurately.
