### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [kaushalmodi/hugo-bare-min-theme#3]
Hello again!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19:
![image](https://user-images.githubusercontent.com/712534/37667654-8c9c5764-2c73-11e8-9266-3464a6f1e92e.png)

Only half of an image fits on the screenshot, should be whole.

**Comment by kaushalmodi** [comment]
Hello!

This one is definitely outside the "bare min" scope.. as it has to do with looks and CSS. *Or if the image is too big, resize it before committing or use the [Image Processing][1] power!*

But you can customize/override the default CSS by adding a `.Site.Params.custom_css` as shown in https://github.com/kaushalmodi/hugo-bare-min-theme/commit/8d789df23db2f8913d95b336b32955617c236d71.

See https://stackoverflow.com/a/11079048/1219634 for setting `img .. max-width` CSS.

[1]: https://gohugo.io/content-management/image-processing/
