### ISSUE TITLE
Archetypes directory missing error

### ISSUE THREAD

**Issue by sombreroEnPuntas** [kaushalmodi/hugo-bare-min-theme#4]
ERROR  
`Unable to find archetypes directory for theme "bare-min" at "/home/$USER/$SITE_DIR/themes/bare-min/archetypes"`

Seems like you need  **archetypes/default.md** file for this to work :)

**Comment by kaushalmodi** [comment]
Oh right, I'll fix that :) 

I never get this error as I never use `hugo new`. I write my posts directly in Emacs/Org mode and export them to Markdown using `ox-hugo`.

**Comment by kaushalmodi** [comment]
But wait, why would the theme require the `archetypes` dir? Isn't that present in your site repo?

**Comment by sombreroEnPuntas** [comment]
On `site`, yes. There is a folder with a default template.  
But seems like setting the **theme** param makes hugo search for that on the theme module.

I am just following the quick start tutorial tho, never used this tool before... not an expert ^^
Here is an example of a working file structure:
https://github.com/nodejh/hugo-theme-cactus-plus/tree/master/archetypes

**Comment by kaushalmodi** [comment]
@sombreroEnPuntas Thanks for reporting this. The issue is now fixed... `hugo new` won't throw any error.
