### ISSUE TITLE
Your theme's demo is not working on the Hugo Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [kaushalmodi/hugo-bare-min-theme#6]
Hi @kaushalmodi 

I noticed that your theme's demo [is not generating](https://themes.gohugo.io/hugo-bare-min-theme/) on the Hugo Themes website.

When I execute the Website Build Script I get the following errors:

```
 ==== PROCESSING  hugo-bare-min-theme  ====== 
Building site for theme hugo-bare-min-theme using its own exampleSite to ../themeSite/static/theme/hugo-bare-min-theme/
ERROR 2018/11/08 15:09:01 render of "page" failed: "hugoThemes/hugo-bare-min-theme/layouts/_default/baseof.html:60:16": execute of template failed: template: _default/single.html:60:16: executing "_default/single.html" at <partial "debugprint....>: error calling partial: Partial "debugprint.css" not found
ERROR 2018/11/08 15:09:01 render of "taxonomyTerm" failed: "hugoThemes/hugo-bare-min-theme/layouts/_default/baseof.html:60:16": execute of template failed: template: _default/terms.html:60:16: executing "_default/terms.html" at <partial "debugprint....>: error calling partial: Partial "debugprint.css" not found
ERROR 2018/11/08 15:09:01 render of "taxonomy" failed: "hugoThemes/hugo-bare-min-theme/layouts/_default/baseof.html:60:16": execute of template failed: template: _default/list.html:60:16: executing "_default/list.html" at <partial "debugprint....>: error calling partial: Partial "debugprint.css" not found
ERROR 2018/11/08 15:09:01 render of "page" failed: "hugoThemes/hugo-bare-min-theme/layouts/_default/baseof.html:60:16": execute of template failed: template: _default/single.html:60:16: executing "_default/single.html" at <partial "debugprint....>: error calling partial: Partial "debugprint.css" not found
FAILED to create exampleSite for hugo-bare-min-theme
```

Can you please look into the above so that your theme's demo is once again generated?

Thanks.

CC / @digitalcraftsman

**Comment by kaushalmodi** [comment]
I'm not sure why that would happen; I just tested it out on 0.51; it built fine: https://app.netlify.com/sites/hugo-bare-min/deploys/5be438bb0ff8d47429ebe82e

See https://hugo-bare-min.netlify.com/ (Hugo version used to build in footer).

**Comment by kaushalmodi** [comment]
Ah, I know why. You can remove this theme from Hugo themes. This theme relies on Hugo theme components to be cloned in the themes dir. I don't think Hugo themes site generation supports that. 

The failure to find debugprint.css is because it comes from the debugprint theme component (see README of this theme for info). 

/cc @bep

**Comment by onedrawingperday** [comment]
Ok @kaushalmodi I will send a PR to remove your theme from Hugo themes. Thanks for looking into this.

**Comment by kaushalmodi** [comment]
On another thought, shouldn't this site generation work fine if this theme repo was recursively cloned? Because I do have the git submodules linked in the exampleSite themes dir: https://github.com/kaushalmodi/hugo-bare-min-theme/tree/master/exampleSite/themes.

**Comment by onedrawingperday** [comment]
Actually this is related to the Hugo Themes Site Build Script. It does not support Theme Components.

So instead of removing your theme I opened the above issue for adding support for Theme Components in the Build Script.

**Comment by digitalcraftsman** [comment]
@kaushalmodi there's also the possibility to "blacklist" your theme, i.e. your theme is still displayed on the theme site but no demo is generated. We also add a comment in the build script stating the reason for being blacklisted.

**Comment by kaushalmodi** [comment]
"blacklist" sounds bad.

Did you mean "whitelist"? You would be allowing publishing of my theme as the theme site setup doesn't handle theme components. As you are "allowing", it would be white listing, right?

**Comment by onedrawingperday** [comment]
Technically it would be whitelisting your theme because in your case the broken Demo is due to a limitation in the Build Script.

See here for examples of blacklisted themes in the Hugo Themes Site Build Script: https://github.com/gohugoio/hugoThemes/blob/master/_script/generateThemeSite.sh#L104-L119

**Comment by digitalcraftsman** [comment]
> "blacklist" sounds bad.

It does, but there's nothing wrong with your theme. It's just the name of the variable in the build script that I had in mind in order to disable the demo of your theme. Hoewever, in @onedrawingperday's link to the build script is saw that there's a also a `noDemo` variable, which I totally forgot.

- blacklisted: you does not show up on the theme site. That's not what we want :wink: 
- noDemo: the demo of a theme will be disabled, but a page with general information about it will be shown. That sounds much better.

**Comment by onedrawingperday** [comment]
Yes noDemo is what is needed in this theme's case.

So @kaushalmodi if you're OK let me know so that I can send a PR to add your theme in the array of the noDemo variable of the Build Script.

Also I suggest that you add a note in your theme's README about the Hugo Themes Site not supporting Theme Components currently mentioning https://github.com/gohugoio/hugoThemes/issues/463 and maybe also add a link to an external demo of your theme (probably with Netlify or whatever suits you).

**Comment by kaushalmodi** [comment]
@digitalcraftsman @onedrawingperday

Thanks. Adding my theme to noDemo is fine. The Homepage button will still point the external demo (https://hugo-bare-min.netlify.com/) as it already does now, I believe.
